---

  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=86400

  # Java

  - name: Ensure Java is installed.
    apt: pkg=default-jdk state=installed

  # Unzip

  - name: Ensure Unzip is installed.
    apt: pkg=unzip state=installed

  #  print("{{ install_user }}")

  - name: Storm | Ensure group install_user exists
    group: name="{{install_user}}" state=present

  - name: Storm | Ensure user install_user exists
    user: name="{{install_user}}" group="{{install_user}}"  home="{{install_user_home}}" createhome="true" shell="/bin/bash"

  - name: create package directory
    file: path="{{packages_root}}" state=directory owner="{{install_user}}" mode=755
